version: '3.8'
services:
  server:
    image: 'nginx:stable-alpine'
    ports:
      - 8000:80
    volumes:
      - ./src:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
      - mysql
      - phpmyadmin
  php:
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
    volumes:
      - ./src:/var/www/html
    links:
      - mysql
  mysql:
    image: mysql
    env_file:
      - ./env/mysql.env
  phpmyadmin:
    image: phpmyadmin
    environment:
      - PMA_HOST=mysql
    links:
      - mysql
    depends_on:
      - mysql
    ports:
      - "8080:80"
  # utility containers used when needed
  composer:
    build: 
      context: ./dockerfiles
      dockerfile: composer.dockerfile
    volumes:
      - ./src:/var/www/html
  artisan:
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
    volumes:
      - ./src:/var/www/html
    entrypoint: ["php","/var/www/html/artisan"]
  npm:
    image: node:14
    working_dir: /var/www/html
    entrypoint: ["npm"]
    volumes:
      - ./src:/var/www/html
